### ISSUE TITLE
stock vessellandedorsplashed is bugged

### ISSUE THREAD

**Issue by Boris-Barboris** [RCrockford/kOS-AtmosphereAutopilot#1]
https://github.com/RCrockford/kOS-AtmosphereAutopilot/blob/master/src/kOS.Addons.AtmosphereAutopilot/kOSDirector.cs#L40

Just fyi, at least a couple of patches ago it was bugged and did not work correctly after first splashdown. AA's FlightModel has a workaround helper that is used by AA controllers, I can recommend it.

**Comment by RCrockford** [comment]
Can you point me at the workaround helper?

**Comment by Boris-Barboris** [comment]
https://github.com/Boris-Barboris/AtmosphereAutopilot/blob/72ebd68ff8894ef0ecbf8a7854e0e971945b88cc/AtmosphereAutopilot/Common.cs#L212

Nvm, if youre in AA namespace this should be used.
False alarm.
